=== Alberto-mt/XML/DTD-validation/Alumnos_dtd/alumnos.dtd
<!ELEMENT alumnos (alumno)+> 
<!ELEMENT alumno (nombre, edad, telefono+, direccion)>
<!ATTLIST alumno dni CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle, numero, ciudad, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>

=== Alberto-mt/XML/DTD-validation/Alumnos_dtd/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">
<alumnos>
	<alumno dni="12345678A">
		<nombre>Juan Garcia</nombre>
		<edad>20</edad>
		<telefono>624555555</telefono>
		<telefono>624555255</telefono>
		<telefono>624555355</telefono>
		<direccion>
			<calle>Avenida de la Fuente</calle>
			<numero>6</numero>
			<ciudad>Alcorcón</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="22345678A">
		<nombre>Ignacio Martín</nombre>
		<edad>25</edad>
		<telefono>624555551</telefono>
		<telefono>624555255</telefono>
		<direccion>
			<calle>Avenida de la Constitución</calle>
			<numero>2</numero>
			<ciudad>Alcorcón</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="32345678A">
		<nombre>Luis Gutierrez</nombre>
		<edad>29</edad>
		<telefono>624555252</telefono>
		<direccion>
			<calle>Calle Mayor</calle>
			<numero>21</numero>
			<ciudad>Alcorcón</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="42345678A">
		<nombre>María Benito</nombre>
		<edad>19</edad>
		<telefono>624555553</telefono>
		<direccion>
			<calle>Calle Espada</calle>
			<numero>7</numero>
			<ciudad>Alcorcón</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="52345678A">
		<nombre>Silvia Fuentes</nombre>
		<edad>33</edad>
		<telefono>624555554</telefono>
		<direccion>
			<calle>Avenida Leganes</calle>
			<numero>33</numero>
			<ciudad>Alcorcón</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="62345678A">
		<nombre>Rocio Sanz</nombre>
		<edad>29</edad>
		<telefono>624555556</telefono>
		<direccion>
			<calle>Avenida Arroyo</calle>
			<numero>45</numero>
			<ciudad>Móstoles</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="72345678A">
		<nombre>Esteban Arribas</nombre>
		<edad>28</edad>
		<telefono>624555557</telefono>
		<direccion>
			<calle>Calle Mayor</calle>
			<numero>2</numero>
			<ciudad>Móstoles</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="82345678A">
		<nombre>Antonio Aguilar</nombre>
		<edad>27</edad>
		<telefono>624555558</telefono>
		<direccion>
			<calle>Calle Grande</calle>
			<numero>4</numero>
			<ciudad>Leganés</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="92345678A">
		<nombre>Rosa Sanchez</nombre>
		<edad>21</edad>
		<telefono>624555559</telefono>
		<direccion>
			<calle>Calle Zarza</calle>
			<numero>7</numero>
			<ciudad>Leganés</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
	<alumno dni="10345678A">
		<nombre>Francisco Mejía</nombre>
		<edad>26</edad>
		<telefono>624555510</telefono>
		<direccion>
			<calle>Calle Arroyoculebro</calle>
			<numero>4</numero>
			<ciudad>Fuenlabrada</ciudad>
			<provincia>Madrid</provincia>
		</direccion>
	</alumno>
</alumnos>
