=== Alberto-mt/XML/DTD-validation/Cancion_2_dtd/Cancion_2.dtd
<!ELEMENT CD (Cancion+, Fecha)>
<!ATTLIST CD
Titulo CDATA #REQUIRED>
<!ELEMENT Cancion (Titulo, Productores, Sello, Compositores, Artista+)>
<!ATTLIST Cancion 
Duracion CDATA #REQUIRED
Anio CDATA #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Productores (Productor+)>
<!ELEMENT Productor (Nombre, Apellido)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellido (#PCDATA)>
<!ELEMENT Sello (#PCDATA)>
<!ELEMENT Compositores (Compositor+)>
<!ELEMENT Compositor (Nombre, Apellido)>
<!ELEMENT Artista (#PCDATA)>
<!ELEMENT Fecha EMPTY>
<!ATTLIST Fecha
Dia CDATA #REQUIRED
Mes CDATA #REQUIRED
Anio CDATA #REQUIRED>

=== Alberto-mt/XML/DTD-validation/Cancion_2_dtd/Cancion_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CD SYSTEM "Cancion_2.dtd">
<CD Titulo="Bon Jovi Grandes Exitos">
	<Cancion Duracion="4:13" Anio="2000">
		<Titulo>Livin' on a Prayer</Titulo>
		<Productores>
			<Productor>
				<Nombre>Luke</Nombre>
				<Apellido>Ebbin</Apellido>
			</Productor>
			<Productor>
				<Nombre>Richie</Nombre>
				<Apellido>Sambora</Apellido>
			</Productor>
			<Productor>
				<Nombre>Max</Nombre>
				<Apellido>Martin</Apellido>
			</Productor>	
		</Productores>
		<Sello>Island</Sello>
		<Compositores>
			<Compositor>
				<Nombre>Jon</Nombre>
				<Apellido>Bon Jovi</Apellido>
			</Compositor>
		</Compositores>
		<Artista>Jon Bon Jovi</Artista>	
	</Cancion>
	<Cancion Duracion="3:45" Anio="1994">
		<Titulo>You Give Love a Bad Name</Titulo>
		<Productores>
			<Productor>
				<Nombre>Luke</Nombre>
				<Apellido>Ebbin</Apellido>
			</Productor>
			<Productor>
				<Nombre>Richie</Nombre>
				<Apellido>Sambora</Apellido>
			</Productor>
			<Productor>
				<Nombre>Max</Nombre>
				<Apellido>Martin</Apellido>
			</Productor>	
		</Productores>
		<Sello>Island</Sello>
		<Compositores>
			<Compositor>
				<Nombre>Jon</Nombre>
				<Apellido>Bon Jovi</Apellido>
			</Compositor>
		</Compositores>
		<Artista>Jon Bon Jovi</Artista>	
	</Cancion>
	<Cancion Duracion="3:44" Anio="1989">
		<Titulo>It's my life</Titulo>
		<Productores>
			<Productor>
				<Nombre>Luke</Nombre>
				<Apellido>Ebbin</Apellido>
			</Productor>
			<Productor>
				<Nombre>Richie</Nombre>
				<Apellido>Sambora</Apellido>
			</Productor>
			<Productor>
				<Nombre>Max</Nombre>
				<Apellido>Martin</Apellido>
			</Productor>	
		</Productores>
		<Sello>Island</Sello>
		<Compositores>
			<Compositor>
				<Nombre>Jon</Nombre>
				<Apellido>Bon Jovi</Apellido>
			</Compositor>
		</Compositores>
		<Artista>Jon Bon Jovi</Artista>	
	</Cancion>
	<Cancion Duracion="3:50" Anio="2000">
		<Titulo>Who Says You Can't Go Home</Titulo>
		<Productores>
			<Productor>
				<Nombre>Luke</Nombre>
				<Apellido>Ebbin</Apellido>
			</Productor>
			<Productor>
				<Nombre>Richie</Nombre>
				<Apellido>Sambora</Apellido>
			</Productor>
			<Productor>
				<Nombre>Max</Nombre>
				<Apellido>Martin</Apellido>
			</Productor>	
		</Productores>
		<Sello>Island</Sello>
		<Compositores>
			<Compositor>
				<Nombre>Jon</Nombre>
				<Apellido>Bon Jovi</Apellido>
			</Compositor>
		</Compositores>
		<Artista>Jon Bon Jovi</Artista>
		<Artista>Jennifer Nettles</Artista>
	</Cancion>
	<Cancion Duracion="5:56" Anio="1989">
		<Titulo>Always</Titulo>
		<Productores>
			<Productor>
				<Nombre>Jon</Nombre>
				<Apellido>Bon Jovi</Apellido>
			</Productor>	
		</Productores>
		<Sello>Island</Sello>
		<Compositores>
			<Compositor>
				<Nombre>Jon</Nombre>
				<Apellido>Bon Jovi</Apellido>
			</Compositor>
		</Compositores>
		<Artista>Jon Bon Jovi</Artista>
	</Cancion>
	<Fecha Dia="02" Mes="05" Anio="2000"/>
</CD>
