=== Alberto-mt/XML/Schema-validation/Cancion_1_xsd/Cancion_1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Cancion">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Titulo" default="Titulo desconocido">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Productores">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Productor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Nombre" default="Nombre desconocido">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="20"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Apellido" default="Apellido desconocido">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="30"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Sello" default="Sello desconocido">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Compositores">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Compositor">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Nombre" default="Nombre desconocido">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="20"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Apellido" default="Apellido desconocido">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="30"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Artista" default="Artista desconocido" maxOccurs="unbounded">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>	
			<xs:attribute name="Duracion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]:[0-5][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Anio" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1900"/> 
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Alberto-mt/XML/Schema-validation/Cancion_1_xsd/Cancion_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Cancion Duracion="4:28" Anio="2000"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Cancion_1.xsd">
	<Titulo>It's my life</Titulo>
	<Productores>
		<Productor>
			<Nombre>Luke</Nombre>
			<Apellido>Ebbin</Apellido>
		</Productor>
		<Productor>
			<Nombre>Richie</Nombre>
			<Apellido>Sambora</Apellido>
		</Productor>
		<Productor>
			<Nombre>Max</Nombre>
			<Apellido>Martin</Apellido>
		</Productor>	
	</Productores>
	<Sello>Island</Sello>
	<Compositores>
		<Compositor>
			<Nombre>Jon</Nombre>
			<Apellido>Bon Jovi</Apellido>
		</Compositor>
	</Compositores>
	<Artista>Jon Bon Jovi</Artista>	
</Cancion>
