=== Alberto-mt/XML/DTD-validation/Cancion_1_dtd/Cancion_1.dtd
<!ELEMENT Cancion (Titulo, Productores, Sello, Compositores, Artista+)>
<!ATTLIST Cancion
Duracion CDATA #REQUIRED
Anio CDATA #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Productores (Productor+)>
<!ELEMENT Productor (Nombre, Apellido)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellido (#PCDATA)>
<!ELEMENT Sello (#PCDATA)>
<!ELEMENT Compositores (Compositor+)>
<!ELEMENT Compositor (Nombre, Apellido)>
<!ELEMENT Artista (#PCDATA)>

=== Alberto-mt/XML/DTD-validation/Cancion_1_dtd/Cancion_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Cancion SYSTEM "Cancion_1.dtd">
<Cancion Duracion="4:28" Anio="2000">
	<Titulo>It's my life</Titulo>
	<Productores>
		<Productor>
			<Nombre>Luke</Nombre>
			<Apellido>Ebbin</Apellido>
		</Productor>
		<Productor>
			<Nombre>Richie</Nombre>
			<Apellido>Sambora</Apellido>
		</Productor>
		<Productor>
			<Nombre>Max</Nombre>
			<Apellido>Martin</Apellido>
		</Productor>	
	</Productores>
	<Sello>Island</Sello>
	<Compositores>
		<Compositor>
			<Nombre>Jon</Nombre>
			<Apellido>Bon Jovi</Apellido>
		</Compositor>
	</Compositores>
	<Artista>Jon Bon Jovi</Artista>	
</Cancion>
